### ISSUE TITLE
Three-level DNS entry doesn't work

### ISSUE THREAD

**Issue by cybik** [masrly/mastodon-link#1]
My personal handle is as such:

```
@root@a.b.c
```

The extension creates a link to:

```
@root@a.b
```

And disregards the `.c` entirely. This can become an issue, especially with a number of "social.x.y" servers running around.

**Comment by indiealexh** [comment]
Oh yeah... Sub domains are a thing. 

Easy fix, give me 30 mins.

**Comment by indiealexh** [comment]
@cybik https://github.com/masrly/mastodon-link/releases/tag/v1.0.1

**Comment by cybik** [comment]
Confirmed!
