### ISSUE TITLE
Feature Request: alternate URL parsing

### ISSUE THREAD

**Issue by cybik** [masrly/mastodon-link#10]
There is one alternate way of "describing" a Mastodon-type user:

```
<BASE_URL>/@<USERNAME>
```

At the time of writing, at least one twitter profile I have in front of me lists his own user as <base_url>/@<his_username>, *without* any http or https in front.

It might be interesting to add a way to recognize this pattern as a valid fediverse user string.

**Comment by indiealexh** [comment]
Trying to remember if I have seen any other sites that example.com/@username pattern...

I think I'll make it optional.

**Comment by indiealexh** [comment]
So far my attempts to make this a think have resulted in EXTREMELY laggy content.
At the moment I am not sure if this feature is possible because of this.

What about if it only matched links containing this?

**Comment by cybik** [comment]
It wouldn't match twitter names containing the "alternate way", but aside from that, it'd be appropriate.
