### ISSUE TITLE
Not working as advertised

### ISSUE THREAD

**Issue by jberculo** [masrly/mastodon-link#3]
Hi! Thanks for this extension! It's exactly what I was looking for. However, it's not working. I do not see the small mastodons in front of the @someone@server texts. My instance has a subdomain.domain.tld format (I have tried the last version)

**Comment by indiealexh** [comment]
Could you please provide some more details, does it work for some or non at all?

If you go here: https://twitter.com/indiealexh do you see the icon on my profile?

Does chrome show you are running version 1.0.1? 
[chrome://extensions/](chrome://extensions/)
<img width="312" alt="image" src="https://user-images.githubusercontent.com/1066212/203620409-e2907a64-40ea-4844-aeb7-44e8d55316dd.png">

**Comment by jberculo** [comment]
Yes, I see the link on your twitter profile, and I am running 1.0.1. I was under the impression that it should also work on other mastodon servers.

For example: I'm logged in on my server, but I am on a profile page on another mastodon server. When I click 'follow' I get a popup with a link. That's annoying. I thought that this extension would also add a link, for example here.
![image](https://user-images.githubusercontent.com/1790980/203620761-bad95dba-5146-4a2a-b320-4087ad4bf9d0.png)

**Comment by indiealexh** [comment]
Ah!

Mastodon instances show usernames as two strings.

"@"
"username@example.com"

So this extension doesn't see this as a matching string.

I could enable this functionality but the main intent was to be able to open profiles from non mastodon sites to avoid the need to copy paste.

I will make a test version for this as I don't know if it will make mastodon viewing funky.

**Comment by indiealexh** [comment]
I have a solution. give me 5 minutes.

**Comment by indiealexh** [comment]
This should do it for you @jberculo 

https://github.com/masrly/mastodon-link/releases/tag/v1.0.2

**Comment by jberculo** [comment]
It does! :) Thanks for your work!
