### ISSUE TITLE
Google Chrome Store Link dead

### ISSUE THREAD

**Issue by p37307** [masrly/mastodon-link#7]
The webstore link is not working.  [https://chrome.google.com/webstore/detail/mastodon-link/nlfdgcdfjnobjocicnddjghdbmgglame](url)

```
404. That’s an error.

The requested URL was not found on this server. That’s all we know.
```

**Comment by indiealexh** [comment]
Its under review, should be available soon.
In the mean time, please use the zip or source code provided.

**Comment by p37307** [comment]
Thanks

**Comment by indiealexh** [comment]
Webstore link now works, but waiting on google reviewing the 1.1.0 version.

**Comment by p37307** [comment]
Got it installed on Microsoft Edge from the Google Chrome Store. Works great. Dashed over to Twitter and it pulled up Mastodon addresses that people put in their profile, too. I posted about it from my instance, oldfriends.live and tagged you in the post.

**Comment by indiealexh** [comment]
Thanks. Hopefully the 1.1.0 version will be approved around Monday. The v1 version doesn't support usernames on instances that use subdomains.
